package grpcapi

import (
	"context"

	"github.com/pingan/monitor-backend/internal/model"
	"github.com/pingan/monitor-backend/internal/service"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Proto stubs — generated by protoc in production, hand-written here as skeleton.
// Real projects: run `protoc --go_out=. --go-grpc_out=. api/proto/monitor.proto`

type RuleServiceServer struct{}

type AlertServiceServer struct {
	svc *service.Service
}

func NewAlertServer(svc *service.Service) *AlertServiceServer {
	return &AlertServiceServer{svc: svc}
}

// ---- Rule CRUD ----

func (s *RuleServiceServer) ListRules(ctx context.Context, req *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "use REST endpoint /api/v1/rules")
}

// ---- Alert operations ----

func (s *AlertServiceServer) ListAlerts(ctx context.Context, req *ListAlertsRequest) (*ListAlertsResponse, error) {
	alerts, err := s.svc.GetAlerts(ctx, int(req.Page), int(req.Size))
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	total, _ := s.svc.GetAlertCount(ctx)
	resp := &ListAlertsResponse{
		Total:  int32(total),
		Alerts: make([]*Alert, 0, len(alerts)),
	}
	for _, a := range alerts {
		resp.Alerts = append(resp.Alerts, alertToProto(&a))
	}
	return resp, nil
}

func (s *AlertServiceServer) ResolveAlert(ctx context.Context, req *ResolveAlertRequest) (*Alert, error) {
	if err := s.svc.ResolveAlert(ctx, req.Id); err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	return &Alert{Id: req.Id, Status: "resolved"}, nil
}

// ---- Helpers (replace with generated code in production) ----

type Alert struct {
	Id         int64
	RuleId     int64
	Hostname   string
	Severity   string
	Metric     string
	Value      float64
	Threshold  float64
	Message    string
	Status     string
	CreatedAt  int64
	ResolvedAt int64
}

type ListAlertsRequest  struct { Page, Size int32 }
type ListAlertsResponse struct {
	Alerts []*Alert
	Total  int32
}
type ResolveAlertRequest struct{ Id int64 }

type ListRulesRequest  struct{}
type ListRulesResponse struct{ Rules []*Rule }
type Rule               struct {
	Id          int64
	Name        string
	Description string
	RuleType    string
	Metric      string
	Operator    string
	Threshold   float64
	DurationSec int32
	Severity    string
	Expression  string
	Enabled     bool
	ChannelIds  []string
	CreatedAt   int64
	UpdatedAt   int64
}
type GetRuleRequest    struct{ Id int64 }
type CreateRuleRequest struct{ Rule *Rule }
type UpdateRuleRequest struct{ Id int64; Rule *Rule }
type DeleteRuleRequest struct{ Id int64 }
type DeleteRuleResponse struct{}

func alertToProto(a *model.Alert) *Alert {
	r := &Alert{
		Id:        a.ID,
		RuleId:    a.RuleID,
		Hostname:  a.Hostname,
		Severity:  string(a.Severity),
		Metric:    a.Metric,
		Value:     a.Value,
		Threshold: a.Threshold,
		Message:   a.Message,
		Status:    string(a.Status),
		CreatedAt: a.CreatedAt.UnixMilli(),
	}
	if a.ResolvedAt != nil {
		r.ResolvedAt = a.ResolvedAt.UnixMilli()
	}
	return r
}

